version: '3.4'

services:
  workshop:
    image: workshop
    build:
      context: .
      dockerfile: src/Workshop/Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Haslo123."
      ACCEPT_EULA: "Y"