version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Haslo123."
      ACCEPT_EULA: "Y"
  workshop.api:
    image: workshop-api
    build:
      context: src/backend/
      dockerfile: ./Workshop.Api/Dockerfile
    ports:
      - "4001:80"
    depends_on:
      - db
  workshop.frontend:
    image: workshop-frontend
    build:
        context: src/frontend/
        dockerfile: ./Dockerfile
    ports:
        - "4000:80"